title: sschalek.github.io
author:
  name: Steven Schalek
description: >- # this means to ignore newlines until "baseurl:"
  Developer notes

domain: sschalek.github.io
url: "https://sschalek.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

header_pages:
  - about.md
# - portfolio.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

#theme: minima
remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/sschalek" }
#   - { platform: twitter, user_url: "https://twitter.com/user" } 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
